[package]
name = "qsharp-ast"
version = "0.1.0"
authors = ["Mathias Soeken <mathias.soeken@outlook.com>"]
license = "MIT"
edition = "2018"

[dependencies]
itertools = "0.10.1"
paste = "1.0.5"
proc-macro2 = "1.0.29"
rug = "1.13.0"
syn = "1.0.76"

[dev-dependencies]
strip_bom = "1.0.0"
